### ISSUE TITLE
Unable to create server keys

### ISSUE THREAD

**Issue by tyler71** [93million/certcache#14]
Following the instructions, I can't get create-keys to generate keys, or show any output at all when running on 3 separate machines

```
docker-compose run --rm certcacheserver create-keys
docker-compose run --rm certcacheserver create-keys --cahkeys /certcache/cahkeys/
```
However, `./cahkeys` remains empty.
```
version: '3.7'
services:
  certcacheserver:
    container_name: certcacheserver
    image: ghcr.io/93million/certcache
    restart: unless-stopped
    ports:
      - '53:53/udp'
      - '53:53/tcp'
      - '80:80/tcp'
      - '4433:4433/tcp'
    volumes:
      - ./cahkeys/:/certcache/cahkeys/:rw
      - ./cache/:/certcache/cache/:rw
    environment:
      CERTCACHE_CERTBOT_EMAIL: ${certbot_email}
    command: ['serve']
```
with .env
```
certbot_email=myemail@domain
```
